version: '3'

services:
  database:
    image: jitesoft/sqlite
    ports:
      - "5432"

  mailer:
    image: schickling/mailcatcher
    ports: 
      - 1025:1025 # smtp server
      - 1080:1080 # web ui